### ISSUE TITLE
Cannot navigate to definition

### ISSUE THREAD

**Issue by jboysen** [aurelia/vscode-extension#113]
**I'm submitting a bug report**

* **Extension Version:**
1.0.5

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Visual studio code version:**
1.41.1

**Screenshot of incorrect highlight**
![image](https://user-images.githubusercontent.com/935849/71668410-1a0b8500-2d69-11ea-8bf7-993550a50fd2.png)

**Current behavior:**
Above error is thrown by extension when Ctrl-clicking a property in an `.bind=""`-expression in the HTML view.

**Expected/desired behavior:**
That VS Code would navigate to the property in the related view-model.

**Comment by jboysen** [comment]
I also noticed this:
https://github.com/aurelia/vscode-extension/blob/f4707ab6fa5f04cd4d27c98450c1db9cc7e637cf/src/server/FileParser/ProcessFiles.ts#L26

Does this mean it will only parse files in /src/-directories?

**Comment by hiaux0** [comment]
Looks like it is currently indeed only setup for `/src`.
Is your repo in question public, so I could try to test in your repo.

**Comment by jboysen** [comment]
Unfortunately it's not :(

**Comment by hiaux0** [comment]
I experience the same issue on my linux machine.
(ext was tested and developed on a mac)

**Comment by hiaux0** [comment]
Fixed by v2.1.0

Feel free to reopen, if issue persists

Corresponding test: https://github.com/aurelia/vscode-extension/blob/3fbeea35ec648cb5c21071847c448303f2ee5a59/tests/features/capabilities/definitions/definitions.feature#L21
