### ISSUE TITLE
Parser error for components with "repeat.for"-binding

### ISSUE THREAD

**Issue by henkeson** [aurelia/vscode-extension#115]
**I'm submitting a bug report**

* **Extension Version:**
1.0.5

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Visual studio code version:**
1.41.1

**HTML/JS/TS of incorrect highlight**
smart auto complete init
failed to parse path c:/my-path/my-component.html
"Parser Error: Unconsumed token of at column 5 in expression [user of users]"
"Error: Parser Error: Unconsumed token of at column 5 in expression [file of errorUploads]\n    at ParserImplementation.err (c:\\Users\\eh47\\.vscode\\extensions\\aureliaeffect.aurelia-1.0.5\\node_modules\\aurelia-binding\\dist\\commonjs\\aurelia-binding.js:2895:11)\n    at ParserImplementation.parseBindingBehavior (c:\\Users\\eh47\\.vscode\\extensions\\aureliaeffect.aurelia-1.0.5\\node_modules\\aurelia-binding\\dist\\commonjs\\aurelia-binding.js:2430:12)\n    at Parser.parse (c:\\Users\\eh47\\.vscode\\extensions\\aureliaeffect.aurelia-1.0.5\\node_modules\\aurelia-binding\\dist\\commonjs\\aurelia-binding.js:2387:80)\n    at AureliaHtmlParser.getAttributeCommands (c:\\Users\\eh47\\.vscode\\extensions\\aureliaeffect.aurelia-1.0.5\\dist\\src\\server\\FileParser\\Parsers\\AureliaHtmlParser.js:80:48)\n    at AureliaHtmlParser.<anonymous> (c:\\Users\\eh47\\.vscode\\extensions\\aureliaeffect.aurelia-1.0.5\\dist\\src\\server\\FileParser\\Parsers\\AureliaHtmlParser.js:35:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (c:\\Users\\eh47\\.vscode\\extensions\\aureliaeffect.aurelia-1.0.5\\dist\\src\\server\\FileParser\\Parsers\\AureliaHtmlParser.js:4:58)\n    at processTicksAndRejections (internal/process/task_queues.js:89:5)"

**Current behavior:**
The message above is written to the Aurelia output when I start VS Code. This error is shown for all components containing an "repeat.for"-binding.

**Expected/desired behavior:**
No error output

* **What is the motivation / use case for changing the behavior?**
Maybe it prevents the VS Code extension from working properly

**Comment by hiaux0** [comment]
Hey, looks like with vCurrent of Aurelia we can't do anything about that.
I could provide a hacky workaround if you like (includes modifying file in `node_modules` in the extension path of aurelia)

> vCurrent's expression parser was never designed to parse for .. of expressions. It also doesn't parse interpolations. Those are part of the syntax interpreter unfortunately.

https://github.com/aurelia/vscode-extension/issues/101#issuecomment-515778153

**Comment by hiaux0** [comment]
We still give an error output, but add the component to the intellisense list.
Hope that is sufficient for now.
