### ISSUE TITLE
Autocomplete for basic events not implemented properly

### ISSUE THREAD

**Issue by bigopon** [aurelia/vscode-extension#12]
**I'm submitting a bug report**

* **Extension Version:**
0.1.7

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Visual studio code version:**
1.7.0-insiders

**Screenshot of incorrect highlight**
![](http://image.prntscr.com/image/671e739299894eb88d356a9b0836da39.png)

**HTML/JS/TS of incorrect highlight**
Basically unexpected event binding option

**Current behavior:**

**Expected/desired behavior:**
![](http://image.prntscr.com/image/b9cc3099f7b74e55b412025d8ea6299e.png)

* **What is the expected behavior?**
Expect all basic events: 
    * Mouse: `click` `mousedown` `mouseup` `mouseover` `mouseout` `mouseenter` `mouseleave` `mousemove`
    * Drag: `dragstart` `dragend` `drag` `dragover` `dragenter` `dragleave` `drop`
    * Focus: `blur` `focus`
    * Keyboard: `keydown` `keypress` `keyup`
    * Form: `change` `input` `submit`
    * Touch: `touchstart` `touchmove` `touchend`
    * Scroll: `wheel` `scroll`

Will have `delegate` and `trigger` options only.

- **NOTE**: Not bubbling events  such as `blur`, `focus`, `mouseenter`, `mouseout`, `scroll` should be shown with `trigger` only

* **What is the motivation / use case for changing the behavior?**
Make Aurelia great

**Comment by eriklieben** [comment]
Sorry, wanted to get a fix out for the syntax highlighting and moved this a bit too fast to production to test if the auto publish to marketplace worked. 

Working on a fix for this.

**Comment by eriklieben** [comment]
Version 0.1.8 is published and contains a fix for this.
I am sorry for the inconvenience, should have tested it better myself.

**Comment by bigopon** [comment]
Just a side question, what happened to the old way of displaying binding options ? It's more awesome if we can `click.` -> [....options]

**Comment by bigopon** [comment]
Another comment is I would like to have quotes options. I have my emmet setup to enclose html attribute value inside single quotes. The reason for this is to help reduce bundle side as there no need for quotes escape.

**Comment by bigopon** [comment]
And thanks for your hardwork 😄 . autocomplete is quiet awesome now

**Comment by eriklieben** [comment]
The old autocomplete stopped working for some unknown reason in version 1.6.0 of vscode. It simply didn't add the auto-complete suggestions anymore. Bit of bad timing for me, but I am happy it is resolved now :-)

I was already looking at re-writing it to a separate service/ process, so it would not interfering with the UI rendering and makes space for doing more processor intensive work during the autocompletion.

The current implementation is very similar to how the default HTML autocomplete/ suggest works and was the fastest way to get it working again. This can be seen as a basic version, will probably grow/ become smarter over time. The current implementation allows us to move towards auto-complete based on the Aurelia plugins you have loaded or components you have created, etc. 

I think that in the future the 'old way' of autocomplete ```value.[options]``` will probably return or some variant of it.

I can add a configuration options for double or single quotes (#13), so it will complete according to your preference.
