### ISSUE TITLE
Missing valid web components

### ISSUE THREAD

**Issue by pkkummermo** [aurelia/vscode-extension#125]
**I'm submitting a bug report**

We're currently not including the component at all if we're having issues with the template (see #115), which is not preferrable as the markup (might) still work. Perhaps if we have a corresponding view we should include the component anyway. We also have the `@noView` decorator which should also be included.

* **Extension Version:**
NA

**Please tell us about your environment:**
* **Operating System:**
NA

* **Visual studio code version:**
NA

**Expected/desired behavior:**
All web components are welcome, both noView and "broken" templates.

**Comment by hiaux0** [comment]
Closed by #127
