### ISSUE TITLE
vscode as a dependency is deprecated

### ISSUE THREAD

**Issue by pkkummermo** [aurelia/vscode-extension#129]
**I'm submitting a chore report**
Bump dependencies and remove old dependencies

* **Extension Version:**
NA

**Please tell us about your environment:**
* **Operating System:**
NA

* **Visual studio code version:**
NA

**Current behavior:**
We're using a deprecated way of running vscode during development. See https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode

**Expected/desired behavior:**
Non usage of deprecated functions is a goal

* **What is the motivation / use case for changing the behavior?**
Keep up to date with vscode way of best practices to get newest and best functionalities

**Comment by hiaux0** [comment]
Closed by #130
