### ISSUE TITLE
Include noView and useView-components in autocomplete

### ISSUE THREAD

**Issue by pkkummermo** [aurelia/vscode-extension#133]
**I'm submitting a bug report**
`@noView` and `@useView` web components should be in autocomplete

* **Extension Version:**
NA

**Please tell us about your environment:**
* **Operating System:**
NA

**Current behavior:**
The components are not included in autocomplete

**Expected/desired behavior:**
They should be

**Comment by hiaux0** [comment]
Closed by #134
