### ISSUE TITLE
Configure path to tsconfig.json

### ISSUE THREAD

**Issue by Seebiscuit** [aurelia/vscode-extension#149]
**I'm submitting a feature request**

* **Extension Version:**
v2.0.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Visual studio code version:**
v1.54.0

My tsconfig is not in the project/folder/workspace VSCode root. Could we add a config entry to set a relative path to the **tsconfig.json**?

**Comment by hiaux0** [comment]
New version releade (2.0.4).
Can you checkout this setting?: 
https://github.com/aurelia/vscode-extension#project

  ```json
    "aurelia.pathToTsConfig": {
      "type": "string",
      "description": "Provide an absolute path to a tsconfig.json"
    }
  ```

You can then verify, that the extension picked up the correct path in the output

![image](https://user-images.githubusercontent.com/30693990/110687988-6827de00-81e1-11eb-834e-aff9bccdd8ce.png)
