### ISSUE TITLE
Extension constantly crashing

### ISSUE THREAD

**Issue by itkfm** [aurelia/vscode-extension#151]
**I'm submitting a bug report**

* **Extension Version:**
2.0.4

**Please tell us about your environment:**
* **Operating System:**
- GNU/Linux (Ubuntu 20.04)
- Windows 10

* **Visual studio code version:**
1.54.1

**Screenshot of incorrect highlight**

![image](https://user-images.githubusercontent.com/53079668/110843258-5b21f200-82a8-11eb-9253-01f39a71eaaf.png)

**HTML/JS/TS of incorrect highlight**

**Current behavior:**

Aurelia extension crashes straight after opening VS Code for non-Aurelia workspaces.
This also effects workspaces where the Aurelia project is located in a subfolder.

```log
[server.ts] 1. onInitialize
[server.ts] 2. onInitialized
[server.ts] 3. Create Aurelia Watch Program
[Info] The Extension is based on this directly:  /home/u/dev/m/server
[INFO]: Path to tsconfig.json detected:
undefined
[carw.ts] 3.4 Initiating a watcher for documentation and fetching changes in custom components
c8:27:56 PM - Starting compilation in watch mode...

error TS5083: Cannot read file '../../tsconfig.json'.
[Info  - 8:27:56 PM] Connection to server got closed. Server will restart.
[server.ts] 1. onInitialize
[server.ts] 2. onInitialized
[server.ts] 3. Create Aurelia Watch Program
[Info] The Extension is based on this directly:  /home/u/dev/m/server
[INFO]: Path to tsconfig.json detected:
undefined
[carw.ts] 3.4 Initiating a watcher for documentation and fetching changes in custom components
c8:27:57 PM - Starting compilation in watch mode...

error TS5083: Cannot read file '../../tsconfig.json'.
[Info  - 8:27:57 PM] Connection to server got closed. Server will restart.
[server.ts] 1. onInitialize
[server.ts] 2. onInitialized
[server.ts] 3. Create Aurelia Watch Program
[Info] The Extension is based on this directly:  /home/u/dev/m/server
[INFO]: Path to tsconfig.json detected:
undefined
[carw.ts] 3.4 Initiating a watcher for documentation and fetching changes in custom components
c8:27:57 PM - Starting compilation in watch mode...

error TS5083: Cannot read file '../../tsconfig.json'.
[Info  - 8:27:57 PM] Connection to server got closed. Server will restart.
[server.ts] 1. onInitialize
[server.ts] 2. onInitialized
[server.ts] 3. Create Aurelia Watch Program
[Info] The Extension is based on this directly:  /home/u/dev/m/server
[INFO]: Path to tsconfig.json detected:
undefined
[carw.ts] 3.4 Initiating a watcher for documentation and fetching changes in custom components
c8:27:57 PM - Starting compilation in watch mode...

error TS5083: Cannot read file '../../tsconfig.json'.
[Info  - 8:27:57 PM] Connection to server got closed. Server will restart.
[server.ts] 1. onInitialize
[server.ts] 2. onInitialized
[server.ts] 3. Create Aurelia Watch Program
[Info] The Extension is based on this directly:  /home/u/dev/m/server
[INFO]: Path to tsconfig.json detected:
undefined
[carw.ts] 3.4 Initiating a watcher for documentation and fetching changes in custom components
c8:27:58 PM - Starting compilation in watch mode...

error TS5083: Cannot read file '../../tsconfig.json'.
[Error - 8:27:58 PM] Connection to server got closed. Server will not be restarted.
```

**Expected/desired behavior:**

* **What is the expected behavior?**

The extension doesn’t get active for non-Aurelia projects without manual tinkering.
Or at least it doesn’t crash verbosely.

* **What is the motivation / use case for changing the behavior?**

Bad first impression to a workmate who was constantly facing the error message after naively installing this extension. Since the very basic syntax highlighting, he even thought that this extension was just straightaway broken and not doing anything.

Note: he’s an Angular user and used to its pretty fancy developer experience.

----
Template is a wall of text. Easy to miss those `major.minor.patch-pre` placeholders. Oups.

**Comment by timfish** [comment]
Opening [this](https://github.com/timfish/bincode-typescript/) repository with vscode and the v2 extension reproduces this issue.

**Comment by hiaux0** [comment]
Ouh not good.

Explanation: 
The extension tries to find a tsconfig.json file in the root.
If it fails to find, then it crashes

I'll look into straight away!

**Comment by hiaux0** [comment]
Fix is live.
It will silently fail now. 

![image](https://user-images.githubusercontent.com/30693990/110947971-17c79200-8341-11eb-91d8-c0e31e4a8aa6.png)
