### ISSUE TITLE
[Bug] expression inside template is triggering binding command instead of typings

### ISSUE THREAD

**Issue by bigopon** [aurelia/vscode-extension#166]
**I'm submitting a bug report**

* **Extension Version:**
2.0.7

**Please tell us about your environment:**
* **Operating System:**
Windows

* **Visual studio code version:**
1.63.1

**Screenshot of incorrect highlight**
![image](https://user-images.githubusercontent.com/9994529/146121800-b86e95de-06ad-4ea9-9f29-e7f2d181d2a6.png)

**Expected/desired behavior:**
It should display some different intellisense

**Comment by hiaux0** [comment]
Looks a bit better now
![image](https://user-images.githubusercontent.com/30693990/157302788-f6084d85-22d2-47ef-94fd-dc204b1b1361.png)
