### ISSUE TITLE
auOpenRelated does not work anymore

### ISSUE THREAD

**Issue by rmja** [aurelia/vscode-extension#169]
**I'm submitting a bug report**

* **Extension Version:**
2.1.2

**Please tell us about your environment:**
* **Operating System:**
* Windows 11

* **Visual studio code version:**
1.63.2

**Current behavior:**
The command auOpenRelated does not seem to exist anymore. Using the command from the command palette and via a keyboard shortcut reports that the command is not found.

**Expected/desired behavior:**
That the auOpenRelated command works as before the recent series of updates.

**Comment by hiaux0** [comment]
Thanks for the report.
Seems like the extension is not activating on Windows/Mac at all. Works on Linux 

I'm trying to push some changes. Not exactly sure if that'll fix it.

**Comment by hiaux0** [comment]
Should be fixed by 2.1.4

### Verified bug
Verified 2.1.2, does not work on Ubuntu/Mac


### Fixed bug
Verified 2.1.4, works on Ubuntu/Mac
