### ISSUE TITLE
Focus binding should have option like a normal non bubbling event, together with binding options

### ISSUE THREAD

**Issue by bigopon** [aurelia/vscode-extension#17]
**I'm submitting a bug report**

* **Extension Version:**
0.1.8

**Please tell us about your environment:**
* **Operating System:**
all

* **Visual studio code version:**
all

* **Current behavior:**
focus event binding is special in Aurelia, but not yet fully supported in the extension. Currently only have 2 options: `call` & `trigger`

* **Expected/desired behavior:**
`focus` binding should have `call`, `trigger`, `bind`, `one-way`, `two-way`, `one-time`

**Comment by eriklieben** [comment]
Thanks!

Updated the code, will release a new version soon with this fix and some other fixes.
