### ISSUE TITLE
HTML attributes containing values with *.ref* break syntax highlighting

### ISSUE THREAD

**Issue by Krossmaskinen** [aurelia/vscode-extension#19]
**I'm submitting a bug report**

* **Extension Version:**
0.1.9

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Visual studio code version:**
1.7.1

**Screenshot of incorrect highlight**
![vscode html highlight bug](https://cloud.githubusercontent.com/assets/1162364/20004649/e8f42dbe-a28d-11e6-93e3-ea6ac93179e4.jpg)

**Reproduce:**
1. Set syntax highlighting to HTML
2. enter `<div data-reference-id="client.referenceId">All markup from here on will be wrongly highlighted</div>`

* **What is the expected behavior?**
Syntax highlighting will break after `.ref`. Adding a second `"` after the closing quotation mark will fix highlighting but will break markup.

* **What is the motivation / use case for changing the behavior?**
Being able to have values in an HTML attribute that contains `.ref`

This bug seems similar to this one: #10

**Comment by eriklieben** [comment]
Thanks for the bug report, I am sorry for the inconvenience.

I will look into this and fix it.

**Comment by eriklieben** [comment]
The issue will be resolved in 0.1.10/ the next release of the extension.

Thanks again!

**Comment by Krossmaskinen** [comment]
Thank YOU!
