### ISSUE TITLE
Autocomplete when using aurelia-bootstrapper

### ISSUE THREAD

**Issue by michaeldwood** [aurelia/vscode-extension#199]
**I'm submitting a bug report** 

* **Extension Version:** 2.1.4

**Please tell us about your environment:**
* **Operating System:** Windows

* **Visual studio code version:** 1.71.2

**Current behavior:**

Autocomplete doesn't work with a project configured with aurelia-bootrapper because "aurelia-bootstrapper" is missing as a dependency/devDependency check at startup.  

**Expected/desired behavior:**

- Create an aurelia project with aurelia-bootstrapper provides the core dependencies.

Implement a check on "aurelia-boostrapper" within [AureliaProjects.ts](https://github.com/aurelia/vscode-extension/blob/a871382bff1394ee3eb8f1e70581579737487d10/server/src/core/AureliaProjects.ts#L349);

As a workaround: `npm install aurelia-cli --save-dev` (whether you plan to use it or not)

**Comment by hiaux0** [comment]
v 2.3.5 pre-release was pushed with a fix for this
(I did not test, just added the checks)
