### ISSUE TITLE
No code completion in string interpolation or ability to go to definition

### ISSUE THREAD

**Issue by cberkley** [aurelia/vscode-extension#211]
**I'm submitting a bug report**

* **Extension Version: v2.1.4**

**Please tell us about your environment:**
* **Operating System: Windows 11**

* **Visual studio code version: 1.75.1**

**Current behavior:**
Primitive public class variables do not show in code completion for string interpolation or binding.

**Expected/desired behavior:**
when I type ${ several choices would show in code completion based on the variables and methods available in the view model.  

Here is the output logs from the Output panel of VSCode: [AureliaVsCodePluginOutputLog.txt](https://github.com/aurelia/vscode-extension/files/10827549/AureliaVsCodePluginOutputLog.txt)

I posted a video showing what I mean.
https://youtu.be/_JFwzGPpTJQ

The code I used to recreate the issue is here:
https://github.com/cberkley/AureliaBugReport
It was generated using npx makes aurelia on February 24th, 2023 using the typescript preset. Then I did add a small name-tag component to illustrate my points.

Steps to recreate:

- do npx makes aurelia
- pick the typescript option with 
- go into my-app.ts
- add public myName = 'foobar';
- go to my-app.html
- add p tag
- then in the p tag type ${ and start typing m
- you get no code completion and the output just shows "Error: No Aurelia components found." over and over again

Thanks for your time.  Please let me know if I am misunderstanding the feature set.

**Comment by tamagosante** [comment]
Really sry I missed this report.
I just tried with the repo you gave (many thanks for that!).

Seems to work for me.
You can try to switch to the pre-release version 2.3.9

https://user-images.githubusercontent.com/30693990/233969363-8f5ba748-b0e4-42d8-9718-a65387f5b227.mp4

**Comment by tamagosante** [comment]
@cberkley

**Comment by cberkley** [comment]
@hiaux0 

Thanks for taking a look at this.  I am still seeing this issue even running pre-release.  Is there a setting I am forgetting?  I have tried disabling all other plugins and I am using the default vscode theme.

Is something wrong with my settings or is something missing tsconfig.json?
[settings.txt](https://github.com/aurelia/vscode-extension/files/11323262/settings.txt)

Again, thank you for your time.  I am excited to get his plugin working on my pc.

https://user-images.githubusercontent.com/11062251/234306920-a3cf4215-9e8d-4f76-8309-f8dd33fbaa3a.mp4

**Comment by cberkley** [comment]
@hiaux0 

I tried reinstalling vscode and it worked.  I now have code completion.  Thanks again for your time.
