### ISSUE TITLE
Adopt SnippetString API

### ISSUE THREAD

**Issue by jrieken** [aurelia/vscode-extension#25]
With the December release VS Code will have real API to define a CompletionItem that is inserted as snippet, for details see https://github.com/Microsoft/vscode/issues/3210. 

In short, we now support a subset of the more common TextMate syntax: `$1`, `$2` etc define tabstops, `${1:value}` and `${2:this is${3:nested}}` placeholders, and `$0` is for the final tabstop. 

The API for this is contained in a new type [`SnippetString`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2035). It can be used as the `insertText` of a [CompletionItem](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2364).

During a transition phase we will still support the internal, unspecified snippet syntax your extension is using but eventually remove it (roughly 2 or 3 milestones from now). 

The language server protocol supports the SnippetString in its next-branch - see https://github.com/Microsoft/vscode/issues/15577#issuecomment-262160802

**Comment by EisenbergEffect** [comment]
@jrieken Thanks for the heads up. We really appreciate you reaching out to us! Also, whenever you are at Microsoft's Redmond campus in the future, ping me. I'd love to meet and talk with you about your work on VS Code.

**Comment by EisenbergEffect** [comment]
@eriklieben We should definitely move on this when we can to stay ahead of these changes.

**Comment by eriklieben** [comment]
Yes! The above is incredible! Thanks @jrieken!

When the old autocompleted stopped working in 1.6.0, I tried to push TextMate snippet string into the insertText param :-) And discovered it didn't work that way, then I started looking at the custom implementation of the HTML language server.  Was looking at how I could refactor that code to be easier to extend and basically, accept TextMate snippet strings. So I am very very happy with this :-)

Will try to get this into the extension during the weekend, my evenings are a bit booked this week. If nothing changes in my schedule, then we will have this ready to release at 1 Dec together with the 1.8.0 release of vscode.

**Comment by eriklieben** [comment]
@jrieken do you maybe know how to get around this issue/ did you also experience this? / how did you solve it :-)

Repository:\vscode-extension [snippetString ≡]> npm install vscode-languageserver-types@next -D
aurelia@0.1.11 Repository:\vscode-extension
`-- vscode-languageserver-types@3.0.1-alpha.6  **invalid**

On trying to install the vnext package of the types I get invalid on each of the 3.0.1 packages, while I am using Typescript 2.0.3.

**Comment by jrieken** [comment]
@aeschli or @dbaeumer will know

**Comment by dbaeumer** [comment]
@eriklieben just test this and it works for me and installs `vscode-languageserver-types@3.0.1-alpha.9`. Are you still seeing the issue.

**Comment by eriklieben** [comment]
@dbaeumer created a new branch and installation works now :-) Thanks!

@jrieken new version of aurelia extension is on it's way with SnippetString, sorry for the long delay.

Thanks all!
