### ISSUE TITLE
Can you add this plugin for vs 2015

### ISSUE THREAD

**Issue by javadbat** [aurelia/vscode-extension#27]
is this plugin can use in vs2015 how can i add it?

**Comment by eriklieben** [comment]
Hi @javadbat,

This is an extension for visual studio code editor (https://code.visualstudio.com/) and not for the full featured version of Visual Studio. 

I found one for the full featured version in the visual studio marketplace (https://marketplace.visualstudio.com/items?itemName=MadsKristensen.AureliaPack) that adds a set of snippets to Visual Studio 2015/17.

Hope this helps,

Erik
