### ISSUE TITLE
Bug in html syntax highlighting when attribute content contains a 'model' keyword

### ISSUE THREAD

**Issue by tdamir** [aurelia/vscode-extension#3]
**I'm submitting a bug report**

* **Library Version:**
0.1.4

**Please tell us about your environment:**
* **Operating System:**
Windows 10

**Current behavior:**
If the attribute value contains a 'model' (ie: value.bind="model.value") then rest of the html is not well highlighted.

**Comment by eriklieben** [comment]
Thanks for submitting this bug request, I am sorry you had an inconvenient experience using the extension. 

I have fixed the issue, and it will be resolved in the next release. I will be checking the other cases in which the same might occur and fix add test cases for them, before create a new release to resolve this bug.

**Comment by tdamir** [comment]
No worries. Thank you!

**Comment by eriklieben** [comment]
A new version is released that includes the fix https://marketplace.visualstudio.com/items?itemName=AureliaEffect.aurelia
