### ISSUE TITLE
[Feature Request] Solarized Theme Addition

### ISSUE THREAD

**Issue by Deterus** [aurelia/vscode-extension#33]
**I'm submitting a feature request**
Would it be possible for a solarized light and dark theme to be added in addition to the default light and dark themes?

**Comment by eriklieben** [comment]
We can probably add them, only need to convert them from the tmlanguage xml format to json for easy usage (dev wise).

**Comment by eriklieben** [comment]
Added in release 0.2.3

Aurelia Solarized dark and Aurelia Solarized light are now included with the extension.

Enjoy.

**Comment by Deterus** [comment]
Thank you so much!!!! I really appreciate it!
