### ISSUE TITLE
[Bug] Special element with opening tag ended with special attribute causes incorrect highlighting

### ISSUE THREAD

**Issue by bigopon** [aurelia/vscode-extension#35]
**I'm submitting a bug report**

* **Extension Version:**
0.2.3

**Please tell us about your environment:**
* **Screenshot of incorrect highlight**
![Incorrect Highlight](http://image.prntscr.com/image/53fe6ff0659543608c9f0e887fa9764a.png)

* **Screenshot of correct highlight**
![Correct Highlight](http://image.prntscr.com/image/90aee6dd6770447887295ae52bd9b628.png)

**Current behavior:**

**Expected/desired behavior:**
* **What is the expected behavior?**
Should correctly highlight

**Edit**
I'm using Monokai theme. When using Aurelia Dark+ theme:
![Incorrect Highlight](http://image.prntscr.com/image/e8e2b75b5f3949458d0e40680a521c02.png)

**Comment by eriklieben** [comment]
Thanks for submitting a bug request, I am sorry you had an inconvenient experience using the extension.

I will look into it and resolve the issue later today (I think/ if my planning won't change :-))

**Comment by eriklieben** [comment]
version 0.2.4 is released which contains a fix for this.

Thanks again!

**Comment by bigopon** [comment]
Great 👍
