### ISSUE TITLE
feat(languageserver): View Model Intellisense in View

### ISSUE THREAD

**Issue by RichiCoder1** [aurelia/vscode-extension#36]
This is a big ask, but it would be great to have auto completion of a view model's properties/methods in the associated view when doing interpolation, bindings, and general expressions. Squiggles when binding to a property/method that doesn't exist on the associated VM (especially w/ typescript) would also be terrific.

**Comment by MeirionHughes** [comment]
Its coming... next version of the [linter ](https://github.com/MeirionHughes/aurelia-template-lint) is going to feed the AST, Declaration info and Issues this extension. Progress has been a little slow in the last 3 months due to 
* getting bogged down in a few edge cases that are extremely difficult to handle via reflection alone. 
* a 7-10 month old baby that is awake until 11pm, or endlessly crying due to teething.

**Comment by RichiCoder1** [comment]
Awesome! And you have my sincerest condolences ;).

**Comment by jmvtrinidad** [comment]
What is the status for this? This will be an awesome feature.

**Comment by eriklieben** [comment]
I am working on making the vscode extension more aware of your code to enable this.

The dev version is currently aware of the things inside your HTML, so it knows which bindings you used and require statements you included, see https://vimeo.com/220275150 for a small demo. Currently, it also understands your public methods/ properties from ts/js files, still need to do a small refactor on that to make it nice and integrate well. 

Once that is in place, I can slowly start adding features to make the extension aware of properties/ methods, etc.

**Comment by jmvtrinidad** [comment]
Nice, is there a way to try this feature?

**Comment by eriklieben** [comment]
Need to look into that, because the vscode marketplace currently doesn't support releasing a beta or preview channel to release preview builds.

**Comment by eriklieben** [comment]
Work for this feature is in this branch https://github.com/aurelia/vscode-extension/tree/languageserver-documents

**Comment by enrico-padovani** [comment]
Hi, just for an update: any plans to add this feature anytime soon? It will really provide a next level of tooling! Cheers

**Comment by matthewcorven** [comment]
@eriklieben  Based on [January 2020 blog post](http://aurelia.io/blog/2020/01/01/aurelia-release-notes-january-2020)  by @EisenbergEffect can this be closed?

**Comment by hiaux0** [comment]
v2 supports this
