### ISSUE TITLE
Wrong auto completion in HTML files

### ISSUE THREAD

**Issue by gbreeze** [aurelia/vscode-extension#37]
Example:
`if.bi` completes to `if.if.bind=""`

Expected: `if.bind=""`

Only aurelia related 'keys' are affected. 

![autocomplete](https://cloud.githubusercontent.com/assets/1906169/22930706/e776e498-f2c1-11e6-92de-b66c2964f68a.gif)

**Comment by eriklieben** [comment]
Thanks for the bug report, I am sorry you are experiencing these issues.

I think this is due to the changes in vscode to move to textmate snippetstrings. They removed the range property which first could be provided to tell vscode what to replace.

Will look into how to resolve this issue.

**Comment by eriklieben** [comment]
Resolved in 0.2.6, sorry for the double release, it was easier to fix than I assumed.
I think the other issue with the dark black theme and CSS should also be resolved.

**Comment by gbreeze** [comment]
Thanks, works fine now. 👍
