### ISSUE TITLE
bug(html-highlighting): When using certain words like 'view', messes up highlighting

### ISSUE THREAD

**Issue by justindra** [aurelia/vscode-extension#40]
**I'm submitting a bug report**

* **Extension Version:**
0.1.4

**Please tell us about your environment:**
* **Operating System:**
Linux (ArchLinux) & Windows 10

* **Visual studio code version:**
1.8.1

**Screenshot of incorrect highlight**
With aurelia extension enabled
![aur1](https://cloud.githubusercontent.com/assets/4289486/23880004/8a68f1ce-089c-11e7-966f-0389f2945b57.png)

Without aurelia extension enabled
![aur2](https://cloud.githubusercontent.com/assets/4289486/23880021/9dae6f84-089c-11e7-934d-54d7e4f2a08d.png)

**Current behavior:**
As you can see, the `view` word is messing up the highlighting for the rest of the html file. 

**Expected/desired behavior:**
 See screenshot above without the aurelia extension enabled.

**Comment by eriklieben** [comment]
This issue was resolved in version 0.1.5 of the extension.

Can you try to upgrade to 0.2.4 the latest version of the extension to see if the issue still occurs in your setup?

Thanks,

Erik

**Comment by timfish** [comment]
I'm using `0.2.7` and see the same issue with `label`:

![image](https://cloud.githubusercontent.com/assets/1150298/25070372/66304414-229c-11e7-9a3a-0601499006ef.png)
