### ISSUE TITLE
Request textDocument/hover failed with message: Cannot read property '1' of null

### ISSUE THREAD

**Issue by ChrisBriggsy** [aurelia/vscode-extension#43]
**I'm submitting a bug report**

* **Extension Version:**
0.3.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Visual studio code version:**
1.11.2

**Current behavior:**
Since updating the extension, when I hover over an aurelia element in my html the following begins to appear constantly in my output window.

```
[Error - 2:26:26 pm] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property '1' of null
  Code: -32603 
```

**Comment by eriklieben** [comment]
Will create a fix and release this later today when I am back home

**Comment by chaskim** [comment]
I don't know if this will help, but just to provide some more details, the problem only occurs for me in inline styles in an .html file:

```css
<template>
  <style>
    ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
    }
  </style>
</template>
```

In the above example, if I hover over any of the css properties or values (like `ul`, `margin`, or `none`), the error appears in the output window. However, hovering over any html element is okay, at least for me (macOS 10.11.6, VS Code 1.11.2).

**Comment by eriklieben** [comment]
Thanks!

version 0.3.2 has a quick fix show at least the annoying error is gone. 

Need to investigate it deeper to see why it isn't providing hover information in cases where it should, like for example with the class attribute.

Sorry for the inconvenience.

**Comment by razvan-panda** [comment]
I am having same problem with Visual Studio Code using the latest HIE.
