### ISSUE TITLE
feat(template-linting): Notify on attr with camel case in mutiple bindings

### ISSUE THREAD

**Issue by bigopon** [aurelia/vscode-extension#44]
Im not sure if this issue should stay in the xtension or main aurelia repo.
I got the problem when coming back to Aurelia after 2 weeks. It was the custom attribute with multiple bindings. So the html was like this

```html
<div someattr='value.bind: some; linkedWith.bind: other'></div>
```

It didnt work as expected becaused i wrote `linkedWith` instead of `linked-with`. It took me 15 to 30 mins every time i come back here after awhile.

I think it will take new aurelia devs even more time to figure out whats going on.

To solve this, maybe xtension is the fastest way to do, but if dev chose to not use it, it would be aurelia's responsibility. Looking further into it, i think aurelia lacks some sort of dev friendly notification in this area, whenever the parser encounters attribute with camel case binding. This can also be extended to use on all attributes. I think the extension is great but aurelia needs to do more to protect devs.

@EisenbergEffect @eriklieben

**Comment by eriklieben** [comment]
This will be resolved once we are able to integrate the linter into the vscode extension, see https://github.com/aurelia/vscode-extension/issues/32 for more information.

**Comment by eriklieben** [comment]
I will close this issue and keep track of it in https://github.com/aurelia/vscode-extension/issues/32 which is about the same issue.
