### ISSUE TITLE
Latest version breaks HTML formatting functionality

### ISSUE THREAD

**Issue by doronguttman** [aurelia/vscode-extension#45]
**I'm submitting a bug report**

* **Extension Version:**
major.minor.patch-pre

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|Linux (distro)|Windows [7|8|8.1|10]

* **Visual studio code version:**
0.3.2

**HTML/JS/TS of incorrect highlight**
any HTML

**Current behavior:**
Pressing Alt-Shift-F does not format the document; the format document option is gone from the command pallet when in an HTML file. Also, any other HTML extension and snippets are not working as well. When disabling the extension it works again.

**Expected/desired behavior:**

Reproduce: 
1. create a new workspace
2. disable all extensions for workspace
3. create HTML file
4. see that file is formatted when doing Format Document (Alt-Shift-F)
5. Enable extension
6. see that file is NOT formatted and that Format Document is not available in command pallet

**Comment by kuechlerm** [comment]
I can see that html files have now the language mode "aurelia HTML" by default. 

Why is this necessary? Now I have to pick between aurelia-syntax support and formatting.

**Comment by bryceg** [comment]
This also breaks any icon packs

**Comment by Lichtjaeger** [comment]
It also breaks script block and style block syntax highlighting.

**Comment by eriklieben** [comment]
Thanks for the feedback.

Will look into this tonight, might need to remove the custom language again and let it override the default html so plugins/ tools for html stay working.

**Comment by tetious** [comment]
This also breaks tag pair (<div></div>) highlighting to suss out those giant div sandwiches. :)

**Comment by eriklieben** [comment]
Everything is set back to html, I think all the above issues are resolved with that. Version 0.3.3 is on it's way, just waiting for build to complete.
