### ISSUE TITLE
Creating an empty html gives UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by B3zo0** [aurelia/vscode-extension#46]
**I'm submitting a bug report**

* **Extension Version:**
0.3.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Visual studio code version:**
1.12.2

**Current behavior:**
Creating an empty html gives this error:
```(node:5524) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): TypeError: Cannot read property 'start' of undefined```

**Expected/desired behavior:**

* **What is the expected behavior?**
Not to have a warning.

**Comment by eriklieben** [comment]
Thanks for the bug report, I am sorry you are experiencing these issues.

I will look into it on Thursday and try to provide a fix.
