### ISSUE TITLE
Request textDocument/completion failed after opening an html tag at a custom element

### ISSUE THREAD

**Issue by B3zo0** [aurelia/vscode-extension#47]
**I'm submitting a bug report**

* **Extension Version:**
0.3.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Visual studio code version:**
1.12.2

**Current behavior:**
Starting to type an html tag after a custom element gives an error: ```Request textDocument/completion failed with message: Cannot read property 'permittedChildren' of undefined
  Code: -32603```
Please take a look at the screencast I made: https://www.screencast.com/t/rRy8s5JADa

**Expected/desired behavior:**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by eriklieben** [comment]
Thank you for the bug request!, I am sorry you are experiencing issues. 
The screencast was very helpful to reproduce the issue.

**Comment by eriklieben** [comment]
New version is released, which should resolve the above issues and some others.
Thank you for your help in resolving the bugs.

## [0.3.4](https://github.com/aurelia/vscode-extension/compare/0.3.3...v0.3.4) (2017-05-29)


### Bug Fixes

* **auto-complete:** add submit event auto complete to form element ([b03ecd2](https://github.com/aurelia/vscode-extension/commit/b03ecd2))
* **auto-complete:** don't auto-complete attibutes inside attribute value ([093a36a](https://github.com/aurelia/vscode-extension/commit/093a36a))
* **auto-complete:** don't auto-complete bindings on wrong spots ([e650d0d](https://github.com/aurelia/vscode-extension/commit/e650d0d))
* **auto-complete:** ignore elements that are currently not registered, resolves [#47](https://github.com/aurelia/vscode-extension/issues/47) ([d5e8002](https://github.com/aurelia/vscode-extension/commit/d5e8002))
* **auto-complete:** use auto-complete from HTML language for closing tag ([180773e](https://github.com/aurelia/vscode-extension/commit/180773e))
* **html-validation:** don't do anything on empty documents, resolves [#46](https://github.com/aurelia/vscode-extension/issues/46) ([40c2c23](https://github.com/aurelia/vscode-extension/commit/40c2c23))


### Features

* **dependencies:** update vscode-language(client/server/server-types) and aurelia-cli ([198dd1f](https://github.com/aurelia/vscode-extension/commit/198dd1f))
* **syntax:** tokenize capture event binding ([2662c01](https://github.com/aurelia/vscode-extension/commit/2662c01))
* **vscode:** update vscode version to 1.12.1 ([559f3c2](https://github.com/aurelia/vscode-extension/commit/559f3c2))
