### ISSUE TITLE
bug(syntax-tokenizer): I18n colorization issue

### ISSUE THREAD

**Issue by enrico-padovani** [aurelia/vscode-extension#48]
**I'm submitting a bug report**

* **Extension Version:**
0.3.4

* **Operating System:**
Windows 10

* **Visual studio code version:**
1.14.2

**Screenshot of incorrect highlight**
![image](https://user-images.githubusercontent.com/7766472/28571625-10a75b58-7144-11e7-99cd-cdb552e81a5a.png)

**Current behavior:**
The string interpolation for params are not correctly highlighted.

* **What is the expected behavior?**
Colorize the last "}"

**Comment by eriklieben** [comment]
Thanks for the bug report, I am sorry for the inconvenience.

I will look into this and fix it.
