### ISSUE TITLE
Bad syntax highlighting with <meta name="referrer">

### ISSUE THREAD

**Issue by Flatta** [aurelia/vscode-extension#5]
**I'm submitting a bug report**

* **VSCode Version:**
1.5.3

* **Library Version:**
0.1.4

* **Operating System:**
Windows 10

**Current behavior:**
![image](https://cloud.githubusercontent.com/assets/11276413/19217992/103a7cbe-8e27-11e6-9050-9720ed8f5b35.png)

**Expected/desired behavior:**
![image](https://cloud.githubusercontent.com/assets/11276413/19218014/b4548164-8e27-11e6-9fdc-88b172966557.png)

**Comment by Flatta** [comment]
Thank you so much, I overlooked a fix again...

**Comment by eriklieben** [comment]
A new version is released that includes the fix https://marketplace.visualstudio.com/items?itemName=AureliaEffect.aurelia

**Comment by Flatta** [comment]
Thank you again.
I just confirmed it working!
