### ISSUE TITLE
feat(auto-complete): add from-view / to-view to data binding suggests

### ISSUE THREAD

**Issue by eriklieben** [aurelia/vscode-extension#53]
- from-view bindings - This is a one-way binding that only pushes from the view to the model. To create symmetry, we've also added the to-view binding as an alias to our standard one-time binding.

Add from-view binding to data binding suggestions.

Add config option to configure the usage of:

- from-view / to-view / one-time
- from-view / to-view
- from-view / one-time

And figure out what would be the best default setting

**Comment by eriklieben** [comment]
Changed it to a configurable setting for the user, which can be set for all or per workspace/project (default functionality of VSCode).

see: https://youtu.be/_zziyhlPwfs

Remaining question to answer: What would be a proper default setting for this configuration?

1) add all (bind / one-way / two-way / one-time / to-view / from-view)
feels like it adds a lot of noise to the list and might be confusing for new users because one-way and to-view are the same, which one should they use?

2) bind / one-way / two-way / one-time and add new from-view
Adds the most recent addition (from-view) to the data binding set. It allows a user that is used to one-way to adopt the change without thinking twice.

3) bind / to-view / from-view / two-way / one-time
removes the one-way by default and advises you to use to-view from-view, might not have a good adoption/ acceptance if you have a code base containing a lot of one-way data binding commands.

**Comment by bigopon** [comment]
If it's easy to make the list configurable, then I think it should be 2 with an option to be either 1/ 3. Otherwise it's should be 3. `one-way` is now deprecated, prolonging it usage would conflict with intention in the core.

**Comment by eriklieben** [comment]
Thanks! 

An idea based on your suggestion; this might be a good option for now:

![one-way-deprecated](https://user-images.githubusercontent.com/1912596/34452977-49d5877e-ed4a-11e7-8983-4d8a0897e1dc.png)

It's a bit more cloudy in the autocomplete, but the user can remove one-way in the configuration settings. Existing users can continue using one-way for now but get a signal that it is deprecated, new users/users starting a new solution will know that they need to use to-view instead.

Then at a later moment in time, we can remove one-way as a default option (and users need to manually add it to the configuration if they still want to use it).

**Comment by bigopon** [comment]
That's awesome. Won't alienate existing user, and promote `to-view` 👍

**Comment by zewa666** [comment]
Lol I didnt get that either but the deprication warning does a perfect job :+1:
