### ISSUE TITLE
Bad syntax highlighting with certain patterns

### ISSUE THREAD

**Issue by Flatta** [aurelia/vscode-extension#6]
**I'm submitting a bug report**

* **VSCode Version:**
1.5.3

* **Library Version:**
0.1.5

* **Operating System:**
Windows 10

I noticed that bad syntax highlighting occurs not only with `referrer` but also with some patterns.
Patterns I found are listed below.
* Begins with `show`, `if`, `view-model`, `repeat.for`
* Begins with `bindable`, `controller` (with no following `-` or `!` or ...)
* Contains `.bind`, `.one-way`, `.two-way`, `.one-time`

**Current behavior:**
![image](https://cloud.githubusercontent.com/assets/11276413/19240939/8e572a36-8f47-11e6-8338-764d6efab468.png)
```html
<template>
  <E A="show">         </E>
  <E A="if">           </E>
  <E A="view-model">   </E>
  <E A="repeat.for">   </E>
  <E A="bindable.">    </E>
  <E A="controller.">  </E>
  <E A="x.bind">       </E>
  <E A="x.one-way">    </E>
  <E A="x.two-way">    </E>
  <E A="x.one-time">   </E>
</template>
```

**Comment by eriklieben** [comment]
Thanks for testing it so thoroughly.

I fixed the regex code to behave correctly in these cases, but require some more time to write tests cases for them. Otherwise, I break something again by fixing something else :-)

Will let you know when a fix is ready.

**Comment by EisenbergEffect** [comment]
Sounds good.

**Comment by bigopon** [comment]
Confirm with this:

![](http://image.prntscr.com/image/2e3992ac64344f558bcef5f84eefe2c8.png)

**Comment by eriklieben** [comment]
@Flatta if you upgrade to v0.1.7 the above issue is resolved, I had some issues publishing to the marketplace.
