### ISSUE TITLE
Invalid linting for `tabindex`

### ISSUE THREAD

**Issue by bigopon** [aurelia/vscode-extension#72]
![image](https://user-images.githubusercontent.com/9994529/35469811-64b1bede-0391-11e8-863c-b8cb2818cd51.png)

**Comment by bigopon** [comment]
Same for text content

![image](https://user-images.githubusercontent.com/9994529/35469843-1d568d66-0392-11e8-8d50-5f7b97d2fff1.png)

or innerhtml

![image](https://user-images.githubusercontent.com/9994529/35469848-3b75f3e0-0392-11e8-89d6-1987f3af5182.png)

**Comment by eriklieben** [comment]
bug was caused by the incorrect implementation of #54
