### ISSUE TITLE
error when used together with emmet

### ISSUE THREAD

**Issue by bigopon** [aurelia/vscode-extension#76]
I got the following error when using emmet:

![image](https://user-images.githubusercontent.com/9994529/35492030-58f625f8-04fe-11e8-8906-ddc6aef9f93a.png)

How to reproduce: Use emmet autocomplete for any tag with class. Error happens at `.` character

**Comment by matthewcorven** [comment]
@bigopon Are you still seeing this error?.  I thought I'd pitch in and take a look at the bug, but I'm not able to reproduce.

VSCode 1.25.0
aurelia extension 1.0.3

**Comment by bigopon** [comment]
@matthewcorven Hey, thanks for checking. Somehow I missed your comment. I'm not sure how to reproduce this behavior any more. Probably too subtle.
