### ISSUE TITLE
Emulating Single File Component (like .vue files) functionality

### ISSUE THREAD

**Issue by larserikfinholt** [aurelia/vscode-extension#77]
**I'm submitting a feature request**
I'm aware of discussions to add SFC support to aurelia. As aurelia is focused on standards, it might not be a good idea to include a .au file (similar to the .vue file)

But what about emulting /simulate this functionality. This might give some ideas:

- If `my-comp.html` `my-comp.ts` and `my-comp.css` are all present in the same directory, then, when opening the html file, add the content of the two other files in a `<script>` and a `<style>` tag.
- This will make it possible to scroll vertically through the three files.
- If you're in a .html file with a root `<template>` tag, and no .ts or .css file exists with the same name, then add a buttons in the bottom of the editor to create a script and a style file.

**What is the motivation / use case for changing the behavior?**
Using aurelia and vue for several project, and I find that the easy navigation in the vue file, and the quick way of adding a small component is of big value. 

This might also be of interest for other frameworks looking for a sfc story.

**Comment by eriklieben** [comment]
Thanks for the feature request, great idea. 

For SFC, follow the work in the https://github.com/aurelia/experiment repository, where a compile/transpile step is added which makes the support for single file components possible.

I will close this issue for now, let's pick it up and look for solutions if the above doesn't work out the way it's planned.
