### ISSUE TITLE
Disable jshint in vscode

### ISSUE THREAD

**Issue by adriatic** [aurelia/vscode-extension#80]
**I'm submitting a feature request**

* **Extension Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Visual studio code version:**
1.20.1

**Current behavior:**

Builidng https://github.com/zewa666/aurelia-store-examples results with a ton of jshint "worthless" error messages like 
![image](https://user-images.githubusercontent.com/2712405/36635395-104c8e9e-1982-11e8-8f40-264d189f6e29.png)

**Expected/desired behavior:**

Not showing any of these errors, since Aurelia apps use eslint. Rahter than advising each Aurelia developer to create 

![image](https://user-images.githubusercontent.com/2712405/36635352-5352c272-1981-11e8-882c-9294537e4e40.png)

it might be more user friendly to have aurelia vscode extension do that instead

See  the **[related issue](https://github.com/zewa666/aurelia-store-examples/issues/3#issue-299952757)**

**Comment by Alexander-Taran** [comment]
![image](https://user-images.githubusercontent.com/1029452/36635844-3cd28f4a-19cd-11e8-958f-424144010327.png)
There is a possibility to do this programmatically.. maybe.. There is a discussion on weather to allow creation of new keys vs only modifying existing ones.
https://github.com/Microsoft/vscode/issues/1396

But how will extention know if it should set this key?
What if one explicitly added jshint and now does not see all the errors?

And to see those errors in vscode in the mentioned repo you have to have installed jshint extention to vscode and have jshint globally installed on your system.
Clearly you have it for a reason. (-:

**Comment by eriklieben** [comment]
This is the default behavior of a vs code extensions. If you install an extension, it can respond to certain file types and will in most cases do this by default. In this case, js hint is responding to an open js file.

You can either disable the extension for a given workspace, like explained above or deinstall the complete extension if you don't use it at all.

**Comment by adriatic** [comment]
@eriklieben based on your comment above, I am not sure whether you got my suggestion, so let me restate it, by reusing the **[text](https://github.com/zewa666/aurelia-store-examples/issues/3#issuecomment-368319439) I wrote for @zewa666.
