### ISSUE TITLE
Aurelia extension suppresses HTML Syntax highlighting

### ISSUE THREAD

**Issue by davidsk** [aurelia/vscode-extension#90]
**I'm submitting a bug report**

* **Extension Version:**
1.0.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Visual studio code version:**
1.25.1

**Current behavior:**

HTML files do not have syntax highlighting applied if Aurelia extension is enabled.

![aurelia-enabled](https://user-images.githubusercontent.com/974827/43358332-e17b0472-9287-11e8-934a-52f0927c1263.png)

**Expected/desired behavior:**

HTML files have syntax highlighting applied.  Disabling the Aurelia extension restores this behaviour

![aurelia-disabled](https://user-images.githubusercontent.com/974827/43358327-a83a5690-9287-11e8-858a-ca24d47776ee.png)

**Comment by eriklieben** [comment]
Hi @davidsk,

Sorry for the inconvenience. I am currently unable to reproduce this on my Windows 10 machine with the same version of code & the plugin. If you open up the Help/ About do you see any difference in versions in there? Or do you by any chance have a custom theme installed? (File/ Preferences / Color Theme)

![image](https://user-images.githubusercontent.com/1912596/43364087-bc24ea4e-9313-11e8-9461-0d10f7301a7c.png)


Thanks!

**Comment by davidsk** [comment]
I have been known to use custom themes but I thought I'd check and, well, it seems okay now.  Thanks anyway.

**Comment by gotling** [comment]
I ran into this problem today. Disabling the Aurelia extension solved it.

# Visual Code
```
Version: 1.31.1 (system setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```
